document.querySelector(".btn1").onclick=function(){ 
    document.querySelector(".btn1").innerHTML="Go To Menu";
    document.querySelector(".btn1").style.cursor="pointer";
}

document.querySelector(".btn2").onclick=function(){ 
    document.querySelector(".btn2").innerHTML="SEC 10 GGN ";
    document.querySelector(".btn2").style.cursor="pointer";
}

document.querySelector(".btn3").onclick=function(){ 
    document.querySelector(".btn3").innerHTML="HAVE SOME SHAKES";
    document.querySelector(".btn3").style.cursor="pointer";
}
